version: '3'

services:
    web:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "180:80"
        volumes:
            - ./app:/app/
        depends_on:
            - app
        container_name: task-ddd-web

    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./app:/app/
        container_name: task-ddd-app