version: '3'

services:
    web:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "180:80"
        volumes:
            - ./app:/var/www/html/app/:rw
        depends_on:
            - app
        container_name: task-ddd-web

    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./app:/var/www/html/app/:rw
            - ./task:/var/www/html/app/var/tmp/task/:rw
        container_name: task-ddd-app
        env_file:
            - ./app/.env
        environment:
            PHP_IDE_CONFIG: "serverName=localhost"
        extra_hosts:
            - "host.docker.internal:host-gateway"